language: python
install:
    - pip install -r requirements.txt
branches:
    only:
        - master
script: coverage run --source=factcoin manage.py test --settings=factcoin.settings.test
after_success:
    - coveralls


sudo: required

services:
  - docker

before_install:
  - docker build -t factycznie/factycznie-backend .

script:
  - coverage run --source=moonsheep setup.py test
  - coveralls

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
